### PR TITLE
Provide access to request and response headers

### LINKED ISSUE #1: Request and Response headers not accessible
It would be useful for the response headers to be available.

For example:
- the GitHub API returns its version and rate limit info in X-headers.
- "ETag" and "Last-Modified" can be useful in mirroring applications.
- "Client-SSL-*" also have user applications.

It looks like `http_req()` can save `$res` in `$self`.  This, along with a suitable access method would solve this. e.g. `$resp = $api->response()` (return the whole response object) and/or `$resp = $api->headers()` (return a hashref or specific header);

Likewise, user-provided request headers can be useful.  E.g. adding "If-Modified", 'If-None_Match" and/or "If-SSL-Cert-Subject" for mirroring/server verification.

Perhaps an optional 3rd argument to get/put/post/delete could be a hashref that's merged with `$headers` in `http_req()`.  e.g. `$headers = (%$headers, %$reqhdrs) if( defined $reqhdrs);`

These examples aren't an exhaustive list.

Of course, there are other approaches...

Thanks for your consideration.

### PR DESCRIPTION
**Pull request by tlhackque**
Adds optional argument to get, put, post and del that allows specifying additional HTTP headers.

Provides header method to list and return headers in response.

Provides response method to return the HTTP::Response object.

Treats HTTP_NOT_MODIFIED as a no-content success return.

fixes #1

### CODE REVIEW

**Comment by tlhackque** [comment]
Note: I reviewed the tests, and these changes don't seem to fit in the test structure, as they access LWP internals.

I manually tested the new methods and verified that they work as expected.

**Comment by tlhackque** [comment]
I've added some examples to the POD.  They come from a real application, somewhat simplified for clarity.

**Comment by geofffranks** [comment]
Thanks!

**Comment by tlhackque** [comment]
Thanks for taking the changes, updating the license and making a prompt release to CPAN.

**Comment by tlhackque** [comment]
Merging back into my fork, noticed that you didn't tag yours with v1.1.0.  

Might want to do that so GitHub shows it as a 'release'.

**Comment by geofffranks** [comment]
No problem! Thanks for the contribution :)

**Pull request merged**
